#!/usr/bin/env python3
"""
Compare the user's browser trajectory CSV against an offline reference trajectory
CSV generated by generate_offline_reference_tumvie.py.

Input CSV format for both trajectories:
    frame,t,x,y,z,yaw_rad,pitch_rad,roll_rad

Outputs:
- aligned_trajectories.csv
- summary.txt
- traj_xy.png
- traj_xz.png
- pos_error.png
- rot_error.png

Alignment modes:
- first_frame_se3   : align estimate to reference using the first pose only
- umeyama_se3       : rigid alignment from all positions (recommended default)
- umeyama_sim3      : similarity alignment with scale

Usage:
  python3 compare_browser_vs_offline_reference.py \
      --est-csv dataset/loop-floor0/tumvi_poses.csv \
      --ref-csv dataset/loop-floor0/offline_reference_poses.csv \
      --output-dir dataset/loop-floor0/compare_outputs
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np


def T_from_Rt(R: np.ndarray, t: np.ndarray) -> np.ndarray:
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = R
    T[:3, 3] = np.asarray(t, dtype=np.float64).reshape(3)
    return T


def invT(T: np.ndarray) -> np.ndarray:
    R = T[:3, :3]
    t = T[:3, 3]
    Ti = np.eye(4, dtype=np.float64)
    Ti[:3, :3] = R.T
    Ti[:3, 3] = -(R.T @ t)
    return Ti


def rot_angle(R: np.ndarray) -> float:
    c = 0.5 * (np.trace(R) - 1.0)
    c = min(1.0, max(-1.0, float(c)))
    return math.acos(c)


def R_from_rpy(roll: float, pitch: float, yaw: float) -> np.ndarray:
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    Rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]], dtype=np.float64)
    Ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]], dtype=np.float64)
    Rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]], dtype=np.float64)
    return Rz @ Ry @ Rx


def euler_yaw_pitch_roll_from_R(R: np.ndarray) -> Tuple[float, float, float]:
    sy = math.sqrt(R[0, 0] * R[0, 0] + R[1, 0] * R[1, 0])
    singular = sy < 1e-6
    if not singular:
        roll = math.atan2(R[2, 1], R[2, 2])
        pitch = math.atan2(-R[2, 0], sy)
        yaw = math.atan2(R[1, 0], R[0, 0])
    else:
        roll = math.atan2(-R[1, 2], R[1, 1])
        pitch = math.atan2(-R[2, 0], sy)
        yaw = 0.0
    return yaw, pitch, roll


def umeyama_alignment(X: np.ndarray, Y: np.ndarray, with_scale: bool = False):
    assert X.shape == Y.shape
    n = X.shape[0]
    if n < 3:
        raise ValueError("Need at least 3 points for Umeyama alignment")

    mu_x = X.mean(axis=0)
    mu_y = Y.mean(axis=0)
    Xc = X - mu_x
    Yc = Y - mu_y

    cov = (Yc.T @ Xc) / n
    U, D, Vt = np.linalg.svd(cov)
    S = np.eye(3)
    if np.linalg.det(U) * np.linalg.det(Vt) < 0:
        S[2, 2] = -1
    R = U @ S @ Vt

    if with_scale:
        var_x = np.mean(np.sum(Xc * Xc, axis=1))
        scale = float(np.trace(np.diag(D) @ S) / max(var_x, 1e-12))
    else:
        scale = 1.0

    t = mu_y - scale * (R @ mu_x)
    return scale, R, t


def load_csv_as_pose_series(path: Path):
    with open(path, "r", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")

    req = ["frame", "t", "x", "y", "z", "yaw_rad", "pitch_rad", "roll_rad"]
    for k in req:
        if k not in rows[0]:
            raise ValueError(f"Missing required column '{k}' in {path}")

    frame = np.array([int(float(r["frame"])) for r in rows], dtype=np.int64)
    t = np.array([float(r["t"]) for r in rows], dtype=np.float64)
    p = np.array([[float(r["x"]), float(r["y"]), float(r["z"])] for r in rows], dtype=np.float64)
    R = np.zeros((len(rows), 3, 3), dtype=np.float64)
    for i, r in enumerate(rows):
        yaw = float(r["yaw_rad"])
        pitch = float(r["pitch_rad"])
        roll = float(r["roll_rad"])
        R[i] = R_from_rpy(roll, pitch, yaw)
    T = np.stack([T_from_Rt(R[i], p[i]) for i in range(len(rows))], axis=0)
    return frame, t, T


def associate_by_frame(est_frame: np.ndarray, est_T: np.ndarray,
                       ref_frame: np.ndarray, ref_T: np.ndarray):
    ref_map: Dict[int, np.ndarray] = {int(f): ref_T[i] for i, f in enumerate(ref_frame)}
    out_est: List[np.ndarray] = []
    out_ref: List[np.ndarray] = []
    out_frame: List[int] = []
    for i, f in enumerate(est_frame):
        if int(f) in ref_map:
            out_est.append(est_T[i])
            out_ref.append(ref_map[int(f)])
            out_frame.append(int(f))
    if len(out_frame) < 3:
        raise ValueError("Too few overlapping frame indices between estimate and reference")
    return np.array(out_frame, dtype=np.int64), np.stack(out_est), np.stack(out_ref)


def apply_alignment(T_series: np.ndarray, scale: float, R: np.ndarray, t: np.ndarray) -> np.ndarray:
    out = T_series.copy()
    for i in range(len(out)):
        out[i, :3, :3] = R @ out[i, :3, :3]
        out[i, :3, 3] = scale * (R @ out[i, :3, 3]) + t
    return out


def align_first_frame(est: np.ndarray, ref: np.ndarray):
    A = ref[0] @ invT(est[0])
    aligned = np.einsum("ij,njk->nik", A, est)
    return aligned, {"mode": "first_frame_se3", "scale": 1.0, "R": A[:3, :3], "t": A[:3, 3]}


def align_umeyama(est: np.ndarray, ref: np.ndarray, sim3: bool = False):
    est_p = est[:, :3, 3]
    ref_p = ref[:, :3, 3]
    scale, R, t = umeyama_alignment(est_p, ref_p, with_scale=sim3)
    aligned = apply_alignment(est, scale, R, t)
    mode = "umeyama_sim3" if sim3 else "umeyama_se3"
    return aligned, {"mode": mode, "scale": scale, "R": R, "t": t}


def ate_translation_rmse(est: np.ndarray, ref: np.ndarray) -> float:
    d = est[:, :3, 3] - ref[:, :3, 3]
    return float(np.sqrt(np.mean(np.sum(d * d, axis=1))))


def ate_rotation_rmse_deg(est: np.ndarray, ref: np.ndarray) -> float:
    errs = []
    for i in range(len(est)):
        dR = ref[i, :3, :3].T @ est[i, :3, :3]
        errs.append(rot_angle(dR) * 180.0 / math.pi)
    errs = np.asarray(errs, dtype=np.float64)
    return float(np.sqrt(np.mean(errs * errs)))


def rpe(est: np.ndarray, ref: np.ndarray, delta: int = 1):
    trans = []
    rot = []
    for i in range(len(est) - delta):
        d_est = invT(est[i]) @ est[i + delta]
        d_ref = invT(ref[i]) @ ref[i + delta]
        d_err = invT(d_ref) @ d_est
        trans.append(np.linalg.norm(d_err[:3, 3]))
        rot.append(rot_angle(d_err[:3, :3]) * 180.0 / math.pi)
    return np.asarray(trans), np.asarray(rot)


def path_length(T: np.ndarray) -> float:
    p = T[:, :3, 3]
    if len(p) < 2:
        return 0.0
    return float(np.sum(np.linalg.norm(np.diff(p, axis=0), axis=1)))


def save_plots(outdir: Path, frames: np.ndarray, est: np.ndarray, ref: np.ndarray):
    estp = est[:, :3, 3]
    refp = ref[:, :3, 3]
    pos_err = np.linalg.norm(estp - refp, axis=1)
    rot_err = np.array([
        rot_angle(ref[i, :3, :3].T @ est[i, :3, :3]) * 180.0 / math.pi for i in range(len(est))
    ], dtype=np.float64)

    plt.figure()
    plt.plot(refp[:, 0], refp[:, 1], label="Offline reference")
    plt.plot(estp[:, 0], estp[:, 1], label="Browser estimate")
    plt.axis("equal")
    plt.grid(True)
    plt.legend()
    plt.xlabel("X (m)")
    plt.ylabel("Y (m)")
    plt.title("Trajectory projection (X-Y)")
    plt.tight_layout()
    plt.savefig(outdir / "traj_xy.png", dpi=160)
    plt.close()

    plt.figure()
    plt.plot(refp[:, 0], refp[:, 2], label="Offline reference")
    plt.plot(estp[:, 0], estp[:, 2], label="Browser estimate")
    plt.axis("equal")
    plt.grid(True)
    plt.legend()
    plt.xlabel("X (m)")
    plt.ylabel("Z (m)")
    plt.title("Trajectory projection (X-Z)")
    plt.tight_layout()
    plt.savefig(outdir / "traj_xz.png", dpi=160)
    plt.close()

    plt.figure()
    plt.plot(frames, pos_err)
    plt.grid(True)
    plt.xlabel("frame")
    plt.ylabel("meters")
    plt.title("Position error")
    plt.tight_layout()
    plt.savefig(outdir / "pos_error.png", dpi=160)
    plt.close()

    plt.figure()
    plt.plot(frames, rot_err)
    plt.grid(True)
    plt.xlabel("frame")
    plt.ylabel("degrees")
    plt.title("Rotation error")
    plt.tight_layout()
    plt.savefig(outdir / "rot_error.png", dpi=160)
    plt.close()


def write_aligned_csv(path: Path, frames: np.ndarray, est: np.ndarray, ref: np.ndarray):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "frame",
            "browser_x", "browser_y", "browser_z",
            "ref_x", "ref_y", "ref_z",
            "browser_yaw", "browser_pitch", "browser_roll",
            "ref_yaw", "ref_pitch", "ref_roll",
            "pos_err_m", "rot_err_deg",
        ])
        for i, fr in enumerate(frames):
            by, bp, br = euler_yaw_pitch_roll_from_R(est[i, :3, :3])
            ry, rp, rr = euler_yaw_pitch_roll_from_R(ref[i, :3, :3])
            pe = float(np.linalg.norm(est[i, :3, 3] - ref[i, :3, 3]))
            re = float(rot_angle(ref[i, :3, :3].T @ est[i, :3, :3]) * 180.0 / math.pi)
            w.writerow([
                int(fr),
                *[f"{v:.9f}" for v in est[i, :3, 3]],
                *[f"{v:.9f}" for v in ref[i, :3, 3]],
                f"{by:.9f}", f"{bp:.9f}", f"{br:.9f}",
                f"{ry:.9f}", f"{rp:.9f}", f"{rr:.9f}",
                f"{pe:.9f}", f"{re:.9f}",
            ])


def write_summary(path: Path, meta: dict, est: np.ndarray, ref: np.ndarray):
    ate_t = ate_translation_rmse(est, ref)
    ate_r = ate_rotation_rmse_deg(est, ref)
    est_len = path_length(est)
    ref_len = path_length(ref)

    with open(path, "w") as f:
        f.write(f"alignment_mode: {meta['mode']}\n")
        f.write(f"scale: {meta['scale']:.9f}\n")
        f.write(f"est_path_length_m: {est_len:.9f}\n")
        f.write(f"ref_path_length_m: {ref_len:.9f}\n")
        f.write(f"ate_translation_rmse_m: {ate_t:.9f}\n")
        f.write(f"ate_rotation_rmse_deg: {ate_r:.9f}\n")
        for d in (1, 10, 20, 50):
            if len(est) > d:
                tr, rr = rpe(est, ref, d)
                f.write(f"rpe_delta_{d}_trans_rmse_m: {np.sqrt(np.mean(tr * tr)):.9f}\n")
                f.write(f"rpe_delta_{d}_rot_rmse_deg: {np.sqrt(np.mean(rr * rr)):.9f}\n")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Compare browser trajectory against offline reference CSV")
    p.add_argument("--est-csv", default="dataset/loop-floor0/tumvi_poses.csv", help="Browser estimate CSV")
    p.add_argument("--ref-csv", default="dataset/loop-floor0/offline_reference_poses.csv", help="Offline reference CSV")
    p.add_argument("--output-dir", default="dataset/loop-floor0/compare_outputs", help="Output directory")
    p.add_argument(
        "--alignment",
        default="umeyama_se3",
        choices=["first_frame_se3", "umeyama_se3", "umeyama_sim3"],
        help="Alignment method before metrics"
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    est_csv = Path(args.est_csv)
    ref_csv = Path(args.ref_csv)
    output_dir = Path(args.output_dir)

    est_frame, est_t, est_T = load_csv_as_pose_series(est_csv)
    ref_frame, ref_t, ref_T = load_csv_as_pose_series(ref_csv)

    frames, est_Tc, ref_Tc = associate_by_frame(est_frame, est_T, ref_frame, ref_T)

    if args.alignment == "first_frame_se3":
        est_al, meta = align_first_frame(est_Tc, ref_Tc)
    elif args.alignment == "umeyama_sim3":
        est_al, meta = align_umeyama(est_Tc, ref_Tc, sim3=True)
    else:
        est_al, meta = align_umeyama(est_Tc, ref_Tc, sim3=False)

    output_dir.mkdir(parents=True, exist_ok=True)
    write_aligned_csv(output_dir / "aligned_trajectories.csv", frames, est_al, ref_Tc)
    write_summary(output_dir / "summary.txt", meta, est_al, ref_Tc)
    save_plots(output_dir, frames, est_al, ref_Tc)

    ate_t = ate_translation_rmse(est_al, ref_Tc)
    ate_r = ate_rotation_rmse_deg(est_al, ref_Tc)
    print(f"[DONE] Outputs written to: {output_dir}")
    print(f"[INFO] matched_frames={len(frames)} alignment={meta['mode']} scale={meta['scale']:.6f}")
    print(f"[INFO] ATE translation RMSE = {ate_t:.6f} m")
    print(f"[INFO] ATE rotation RMSE    = {ate_r:.6f} deg")


if __name__ == "__main__":
    main()
